function getAllCategories() {
    return [
          {
            "objectId": "2A672EMvxr",
            "name": "Celulares",
            "createdAt": "2020-05-25T17:22:51.503Z",
            "updatedAt": "2020-06-22T17:34:00.789Z",
            "css": "fas fa-mobile-alt"
          },
          {
            "objectId": "D2CS8xFs9t",
            "name": "Portátiles",
            "createdAt": "2020-05-25T17:22:58.896Z",
            "updatedAt": "2020-06-22T17:34:07.718Z",
            "css": "fas fa-laptop"
          },
          {
            "objectId": "UnDAn5xCj9",
            "name": "Televisores",
            "createdAt": "2020-05-25T17:23:05.440Z",
            "updatedAt": "2020-06-22T17:34:16.872Z",
            "css": "fas fa-tv"
          },
          {
            "objectId": "q4NpRVudDX",
            "name": "Videojuegos",
            "createdAt": "2020-05-25T17:23:15.277Z",
            "updatedAt": "2020-06-22T17:34:25.046Z",
            "css": "fas fa-gamepad"
          }
        ]
}

function getAllProducts() {
  return [
      {
        "objectId": "YZwKUUFlOk",
        "name": "Celular iPhone 6 32GB 4G Plateado",
        "trademark": "APPLE",
        "reference": "iPhone 6 32GB",
        "description": "El iPhone 6 tiene una increíble pantalla Retina HD de 4,7 pulgadas, dos cámaras espectaculares y muchas funcionalidades avanzadas.\n\nTodo en un diseño unibody impecable.",
        "specifications": "<p>- Tamaño de la pantalla:  Retina HD de 4.7 pulgadas</p>\n<p>- Cámara posterior: 8MP con Focus Pixels y flash True Tone</p>\n<p>- Cámara frontal: 1.2 FaceTime HD</p>\n<p>- Memoria interna: 32GB</p>\n<p>- Núcleos del procesador: 2</p>\n<p>- Capacidad de la batería: 1800mAh</p>\n<p>- Carga rápida: No</p>\n<p>- Flash frontal: No</p>\n<p>- Cámara frontal secundaria: No</p>\n<p>- Cámara posterior secundaria: No</p>\n<p>- Marca y modelo del procesador: Chip A8 con con procesador de movimiento M8</p>\n<p>- Velocidad del procesador: 1.4 GHz</p>\n<p>- Memoria RAM: 1GB</p>",
        "value": 782900,
        "availability": 4,
        "category": "Celulares",
        "createdAt": "2020-06-09T02:59:52.190Z",
        "updatedAt": "2020-07-01T03:57:30.557Z",
        "photoUrl": "http://drive.google.com/uc?export=view&id=17lryjuVq4KBcrXicrWr87RsYlJww9Apb"
      },
      {
        "objectId": "K1Dgyp2J06",
        "name": "Celular Motorola One Action 128GB",
        "reference": "Motorola One Action",
        "trademark": "MOTOROLA",
        "description": "Con el sistema de tres cámaras del nuevo Motorola One action, podrás capturar más momentos inolvidables gracias a su Action Cam para un agarre. Triple Cámara captura mejores momentos con enfoque rápido. Pantalla ultra amplia de 6.3” para disfrutar más contenidos. 128GB de almacenamiento Lleva contigo música y películas.",
        "specifications": "<p>- Tamaño de la pantalla: 6.3 pulgadas</p>\n<p>- Cámara posterior: 12 + 5 + 4 MPX</p>\n<p>- Cámara frontal: 12MP</p>\n<p>- Memoria interna: 128GB</p>\n<p>- Núcleos del procesador: Octa Core</p>\n<p>- Capacidad de la batería: 3500mAh</p>\n<p>- Carga rápida: Sí</p>\n<p>- Flash frontal: Sí</p>\n<p>- Cámara frontal secundaria: No</p>\n<p>- Cámara posterior secundaria: 5MP</p>\n<p>- Marca y modelo del procesador: Motorola XT2013-1</p>\n<p>- Velocidad del procesador: 2.2 GHz</p>\n<p>- Memoria RAM: 4GB</p>",
        "value": 689900,
        "availability": 10,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1kXbCznoYQzHNiopaXhT1mD0yytalldJ5",
        "category": "Celulares",
        "createdAt": "2020-06-24T14:50:47.109Z",
        "updatedAt": "2020-06-30T20:54:20.351Z"
      },
      {
        "objectId": "VgtiXDtm3Z",
        "name": "Celular iPhone XR 64GB  4G Negro",
        "reference": "iPhone XR",
        "trademark": "APPLE",
        "description": "<p>Brillante. Por donde lo veas.El iPhone Xr tiene una pantalla Liquid Retina de 6,1 pulgadas, el LCD más avanzado de la industria.Face ID avanzado. El chip más inteligente y potente en un smartphone. Un sistema de cámara revolucionario. Y además, está disponible en seis novedosos acabados. La pantalla tiene las esquinas redondeadas. Si se mide en forma de rectángulo, la pantalla del iPhone Xr tiene 6,06 pulgadas en diagonal. El área real de visualización es menor. </p>\n\n<p>Nueva Liquid Retina. La nueva pantalla del iPhone XR es el LCD más avanzado de la industria. Su innovador diseño retroiluminado lleva esta increíble pantalla hasta las esquinas para que disfrutes de colores más reales hasta el último milímetro de sus bordes.</p>\n\n<p>Materiales extraordinarios. El vidrio frontal más resistente jamás usado en un smartphone. Bordes de aluminio de calidad aeroespacial fabricados con la más alta precisión. Resistencia al agua y al polvo. Y seis novedosos acabados.</p>\n\n<p>Face ID avanzado. Cuando tu cara es tu contraseña, todo es simplemente más seguro. Con sólo una mirada, puedes desbloquear tu iPhone e iniciar sesión en apps. Es el sistema de reconocimiento facial más seguro en un smartphone. Y ahora es aún más rápido.</p>",
        "specifications": "<p>- Tamaño de la pantalla: 6.1 pulgadas</p>\n<p>- Cámara posterior: 12MP</p>\n<p>- Cámara frontal: 7MP</p>\n<p>- Memoria interna: 64GB</p>\n<p>- Núcleos del procesador: 6</p>\n<p>- Capacidad de la batería: 2942mAh</p>\n<p>- Carga rápida: Si</p>\n<p>- Flash frontal: No</p>\n<p>- Cámara frontal secundaria: No</p>\n<p>- Cámara posterior secundaria: No</p>\n<p>- Marca y modelo del procesador: Apple A12 Bionic</p>\n<p>- Velocidad del procesador: 2.49 GHz</p>\n<p>- Memoria RAM: 3GB</p>",
        "value": 2899900,
        "availability": 11,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1imw0LxY1rZAaSiH3N1-G1Os8sZPIne64",
        "category": "Celulares",
        "createdAt": "2020-06-25T02:21:34.475Z",
        "updatedAt": "2020-06-30T20:54:46.874Z"
      },
      {
        "objectId": "Ab0oa6os8m",
        "name": "Videojuego Assassin's Creed Valhalla",
        "reference": "Assassin's Creed Valhalla",
        "trademark": "PLAYSTATION",
        "description": "Assassin's Creed Valhalla es una nueva entrega de la saga de aventura y acción histórica a cargo de Ubisoft ambientada en la era vikinga. Ponte en la piel de Eivor y lidera a tu clan desde los gélidos páramos de Noruega hasta un nuevo hogar en los exuberantes campos de la Inglaterra del siglo IX. Funda tu asentamiento, conquista esa tierra hostil cueste lo que cueste y gánate un lugar en el Valhalla. La Inglaterra de la era vikinga es una nación fracturada, plagada de ruines señores feudales y reinos en guerra, pero bajo ese caos yace una tierra rica e indómita que aguarda a que alguien la conquiste.",
        "specifications": "<p>- Plataforma: PS4</p>\n<p>- Número de jugadores: 1</p>\n<p>- Versión: 1</p>\n<p>- Juego en línea: No</p>\n<p>- Idioma: Español</p>\n<p>- Hecho en: China</p>\n<p>- Género de videojuegos: Acción</p>\n<p>- Clasificación: M (+17 años)</p>\n<p>- Nombre del videojuego: Assassin's Creed Valhalla</p>",
        "value": 269900,
        "availability": 6,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1sQwHWvu29h63dfMSdSq-iQgM1IHnwZA8",
        "category": "Videojuegos",
        "createdAt": "2020-06-28T21:58:28.116Z",
        "updatedAt": "2021-10-14T00:53:39.547Z"
      },
      {
        "objectId": "xBvEt0Tf9Q",
        "name": "Videojuego Days Gone",
        "reference": "Days Gone",
        "trademark": "PLAYSTATION",
        "description": "Days Gone es un videojuego de acción y horror de supervivencia ambientado en un entorno de mundo abierto, post-apocalíptico y jugado desde una perspectiva en tercera persona. El jugador toma el control del protagonista del juego, Deacon St. John (Samuel Witwer), un cazarrecompensas que prefiere vivir una vida peligrosa a campo abierto que esconderse en campamentos en lo más profundo del bosque. El juego tiene lugar dos años después de que se produjo una pandemia global que mató a casi toda la humanidad, y transformó a millones de personas en \"Fenómenos\", criaturas sin sentido tipo zombi que están evolucionando rápidamente.",
        "specifications": "<p>- Plataforma: PS4</p>\n<p>- Número de jugadores: 1</p>\n<p>- Versión: 1</p>\n<p>- Juego en línea: No</p>\n<p>- Idioma: Español</p>\n<p>- Hecho en: China</p>\n<p>- Género de videojuegos: Terror</p>\n<p>- Clasificación: M (+17 años)</p>\n<p>- Nombre del videojuego: Days Gone</p>",
        "value": 229900,
        "availability": 5,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1siHG6cbcbIReVSJG7Rua-0BR7YnAC2H0",
        "category": "Videojuegos",
        "createdAt": "2020-06-28T22:04:26.590Z",
        "updatedAt": "2021-10-14T00:48:52.805Z"
      },
      {
        "objectId": "FDRSVMJR8J",
        "name": "Videojuego Doom Eternal",
        "reference": "Doom Eternal",
        "trademark": "PLAYSTATION",
        "description": "<p>Disfruta de una combinación de velocidad y potencia sin igual abriéndote paso a lo bestia por diferentes dimensiones en este sangriento shooter en primera persona repleto de acción desarrollado por el estudio que contribuyó a definir el género.</p>\n\n<p>Te pondrás en la piel de DOOM Slayer y volverás a la Tierra para descubrir que el planeta ha sufrido una invasión demoníaca.</p>\n\n<p>Descubre los orígenes de Slayer y su incansable misión de arrasar el infierno en el modo campaña individual o participa en la intensa competición de BATTLEMODE, la nueva experiencia multijugador 2 contra 1 creada por id Software.</p>",
        "specifications": "<p>- Plataforma: PS4</p>\n<p>- Número de jugadores: 1</p>\n<p>- Versión: 1</p>\n<p>- Juego en línea: Si</p>\n<p>- Idioma: Inglés</p>\n<p>- Hecho en: China</p>\n<p>- Género de videojuegos: Acción</p>\n<p>- Clasificación: M (+17 años)</p>\n<p>- Nombre del videojuego: Doom Eternal</p>",
        "value": 269900,
        "availability": 5,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1msr1MdsUV2hrXPmMRI-nmKP-D5XPXHLc",
        "category": "Videojuegos",
        "createdAt": "2020-06-28T22:06:42.688Z",
        "updatedAt": "2021-10-14T00:52:14.955Z"
      },
      {
        "objectId": "lQpV427CmX",
        "name": "Videojuego The Last Of Us 2",
        "reference": "The Last Of Us 2",
        "trademark": "PLAYSTATION",
        "description": "Cinco años después de su peligroso viajes a través de unos Estados Unidos postpandémicos, Ellie y Joel se han asen-tado en Jackson, Wyoming. Vivir en una próspera comunidad de supervivientes les ha otorgado paz y estabilidad a pesar de la amenaza constante que suponen los infectados y otros viajeros más desesperados.A raíz de unos violentos acontecimientos que truncan esa paz, Ellie se embarca en un viaje sin descanso para hacer justicia y conseguir pasar página. A medida que va dando caza, uno a uno, a los responsables, tendrá que enfrentarse a las devastadoras consecuencias físicas y emocionales de sus actos.",
        "specifications": "<p>- Plataforma: PS4</p>\n<p>- Número de jugadores: 1</p>\n<p>- Versión: 2</p>\n<p>- Juego en línea: No</p>\n<p>- Idioma: Español</p>\n<p>- Hecho en: China</p>\n<p>- Género de videojuegos: Aventura</p>\n<p>- Clasificación: M (+17 años)</p>\n<p>- Nombre del videojuego: The Last Of Us 2</p>",
        "value": 329900,
        "availability": 10,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1LFiqrm6sPgvnTAVPUzSQrFcxN7KZWjQb",
        "category": "Videojuegos",
        "createdAt": "2020-06-28T22:20:44.064Z",
        "updatedAt": "2020-07-01T02:56:17.946Z"
      },
      {
        "objectId": "INplmHRbBW",
        "name": "Portátil Lenovo LEGION Y540-15IRH-PG0",
        "reference": "LEGION Y540-15IRH-PG0",
        "trademark": "LENOVO",
        "description": "Esta laptop de 15,6” lleva el rendimiento de los juegos a un nuevo nivel. Sus especificaciones de última generación te garantizan una gran potencia. Optimizada térmicamente para funcionar de forma más fría y silenciosa con un teclado de tamaño completo retroiluminado en blanco, la laptop Legion Y540 de Lenovo está preparada para aquellos que demandan juegos dondequiera que la vida los lleve.",
        "specifications": "<p>- Procesador: Intel Core i5</p>\n<p>- Memoria RAM: 8GB</p>\n<p>- Tamaño de la pantalla: 15 pulgadas</p>\n<p>- Disco duro HDD:</p>\n<p>- Unidad de estado sólido SSD: No aplica</p>\n<p>- Núcleos del procesador: Quad Core</p>\n<p>- Memoria total (RAM + Intel Optane): 8 GB</p>\n<p>- Velocidad del procesador: 2.4 GHz</p>\n<p>- Velocidad máxima del procesador: 4.1 GHz</p>\n<p>- Modelo del procesador: Intel Core i5-9300H</p>",
        "value": 4459900,
        "availability": 5,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1ell_8rK8kdPToV0oYSms6Yal0AfF4IgB",
        "category": "Portátiles",
        "createdAt": "2020-06-28T22:24:03.667Z",
        "updatedAt": "2020-06-30T22:20:08.212Z"
      },
      {
        "objectId": "41soFg9TKj",
        "name": "Portátil Asus Vivobook X512DK Ryzen5",
        "reference": "Asus X512DK-BR288T",
        "trademark": "ASUS",
        "description": "Ya sea en el trabajo o jugando, ASUS VivoBook 15 es la laptop más compacta que te sumerge en lo que sea vayas hacer. Su nueva pantalla NanoEdge sin marcos, alardea su ultradelgado bisel 5.7mm, dando un increíble ratio de 87% pantalla-a-cuerpo para lograr sumergirte en sus supremos visuales.",
        "specifications": "<p>- Memoria RAM: 8GB</p>\n<p>- Tamaño de la pantalla: 15.6 pulgadas</p>\n<p>- Disco duro HDD: No aplica</p>\n<p>- Unidad de estado sólido SSD: 512GB</p>\n<p>- Núcleos del procesador: Quad Core</p>\n<p>- Memoria total (RAM + Intel Optane): 8GB</p>\n<p>- Velocidad del procesador: 2.1 GHz</p>\n<p>- Tarjeta de Video: AMD Radeon RX540X</p>\n<p>- Modelo del procesador: AMD Ryzen 5 3500U</p>",
        "value": 2529900,
        "availability": 10,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1ysBE1DcSUuEclhqT_1dgd_XQnDzp6dy6",
        "category": "Portátiles",
        "createdAt": "2020-06-28T22:27:17.174Z",
        "updatedAt": "2020-06-30T22:18:47.311Z"
      },
      {
        "objectId": "Hj3ESjbTLc",
        "name": "Portátil Macbook Pro 13.5\"",
        "reference": "MWP52E/A",
        "trademark": "APPLE",
        "description": "Procesador: Intel Core I5 10th Generation 2.0 GHz. Sistema Operativo: MacOs Catalina. Memoria RAM: 16 GB. Disco Sólido: 1TB. Pantalla: 13.3\" Pulgadas Intel Iris Plus Graphics.",
        "specifications": "<p>- Procesador: Intel Core i5</p>\n<p>- Memoria RAM: 16GB</p>\n<p>- Tamaño de la pantalla: 13.5 pulgadas</p>\n<p>- Disco duro HDD:</p>\n<p>- Unidad de estado sólido SSD: 1TB</p>\n<p>- Núcleos del procesador: Octa Core</p>\n<p>- Memoria total (RAM + Intel Optane): 8 GB</p>\n<p>- Velocidad del procesador: 1.4 GHz</p>\n<p>- Velocidad máxima del procesador: 2.0 GHz</p>\n<p>- Modelo del procesador: Intel Core i5</p>",
        "value": 6000000,
        "availability": 5,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1Ib5cX7Ql1kxSC96oB-BROOaW9V76oMZC",
        "category": "Portátiles",
        "createdAt": "2020-06-28T22:32:42.488Z",
        "updatedAt": "2020-07-01T04:15:05.015Z"
      },
      {
        "objectId": "wyZ8aAnOm0",
        "name": "Portátil Huawei Matebook D 15\" AMD R5",
        "reference": "Matebook D",
        "trademark": "HUAWEI",
        "description": "<p>Sumérgete en las 15 pulgadas de la hermosa pantalla IPS FullView. Con una increíble relación pantalla-cuerpo de 87% y bordes ultradelgados que se han reducido a sólo 5,3 mm, es perfecto para ver películas, crear o trabajar.</p>\n\n<p>Procesador: AMD R5 3500U 2.1 Ghz - 3.7 Ghz. Sistema Operativo: Windows 10 Home. Memoria RAM: 8 GB. Disco Sólido: 256 GB. Pantalla:15\" Pulgadas.</p>",
        "specifications": "<p>- Procesador: AMD R5</p>\n<p>- Memoria RAM: 8GB</p>\n<p>- Tamaño de la pantalla: 15 pulgadas</p>\n<p>- Disco duro HDD: 256 GB</p>\n<p>- Unidad de estado sólido SSD: 128GB</p>\n<p>- Núcleos del procesador: Quad Core</p>\n<p>- Memoria total (RAM + Intel Optane): 4 GB + 16 GB</p>\n<p>- Velocidad del procesador: 2.1 Ghz - 3.7 Ghz</p>\n<p>- Velocidad máxima del procesador: 3.9 GHz</p>\n<p>- Modelo del procesador: AMD R5 3500U</p>",
        "value": 2549900,
        "availability": 5,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1Jt36ROE51ZIO4YMO--AiSaTaE2zDKJnK",
        "category": "Portátiles",
        "createdAt": "2020-06-28T22:35:58.158Z",
        "updatedAt": "2020-07-01T04:09:30.014Z"
      },
      {
        "objectId": "jUTO6IUARJ",
        "name": "Portátil Hp 15.6\" Intel Core i5 4GB 1TB",
        "reference": "15-dy1001la",
        "trademark": "HP",
        "description": "Procesador: Intel Core i3. Memoria RAM: 4GB +16GB Optane. Tamaño de la pantalla: 15.6 pulgadas. Disco duro HDD: No aplica. Unidad de estado sólido SSD: 256GB",
        "specifications": "<p>- Procesador: Intel Core i3</p>\n<p>- Memoria RAM: 4GB +16GB Optane</p>\n<p>- Tamaño de la pantalla: 15.6 pulgadas</p>\n<p>- Disco duro HDD: No aplica</p>\n<p>- Unidad de estado sólido SSD: 256GB</p>\n<p>- Núcleos del procesador: Dual Core</p>\n<p>- Memoria total (RAM + Intel Optane): 256GB + 16GB</p>\n<p>- Velocidad del procesador: 1.2 GHz</p>\n<p>- Velocidad máxima del procesador: 3.4 GHz</p>\n<p>- Modelo del procesador: Intel Core i3-1005G1</p>",
        "value": 1599900,
        "availability": 5,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1StJ5wMCSEuZi_J1-AWyDnVDBAx6YrryH",
        "category": "Portátiles",
        "createdAt": "2020-06-28T22:39:05.539Z",
        "updatedAt": "2020-07-01T04:10:20.584Z"
      },
      {
        "objectId": "htQYTPMzSD",
        "name": "Portátil Dell g3 15\" Core i7 8gb",
        "reference": "G3",
        "trademark": "DELL",
        "description": "Procesador: Intel Core i7. Memoria RAM: 8GB. Tamaño de la pantalla: 15.6 pulgadas. Disco duro HDD: 1TB. Unidad de estado sólido SSD: 128GB",
        "specifications": "<p>- Procesador: Intel Core i7</p>\n<p>- Memoria RAM: 8GB</p>\n<p>- Tamaño de la pantalla: 15.6 pulgadas</p>\n<p>- Disco duro HDD: 1TB</p>\n<p>- Unidad de estado sólido SSD: 128GB</p>\n<p>- Núcleos del procesador: Hexa Core</p>\n<p>- Memoria total (RAM + Intel Optane): 8 GB</p>\n<p>- Velocidad del procesador: 2.20 GHz</p>\n<p>- Velocidad máxima del procesador: 4.10 GHz</p>\n<p>- Modelo del procesador: Intel Core i7-8750H</p>",
        "value": 4890000,
        "availability": 12,
        "photoUrl": "http://drive.google.com/uc?export=view&id=10mVMF7HUOVUKpGnlAOwoCSO5NWVcf_Yv",
        "category": "Portátiles",
        "createdAt": "2020-06-28T22:43:04.804Z",
        "updatedAt": "2020-07-01T04:12:25.286Z"
      },
      {
        "objectId": "1nBnntbHFI",
        "name": "Portátil Gamer Acer 15.6\" Intel Core i5",
        "reference": "AN515-54-51BN",
        "trademark": "ACER",
        "description": "<p>Domine el mundo de los juegos con la potencia y el rendimiento combinados de los gráficos NVIDIA® GeForce® GTX 1050 y un procesador Intel® Core™ i5 novena generación.</p>\n\n<p>Configure su laptop para conseguir la máxima velocidad y un gran almacenamiento con dos ranuras para SSD M.2 PCIe1.</p>\n\n<p>Tarjeta Gráfica: NVIDIA GEFORCE GTX 1050 3GB DDR5. Disco Duro: 1TB. Procesador: Intel Core i5 9300H 2,40 GHz. Memoria RAM: 8 GB. Pantalla: 15.6\" Pulgadas. Sistema Operativo: Windows 10.</p>",
        "specifications": "<p>- Procesador: Intel Core i5</p>\n<p>- Memoria RAM: 8GB</p>\n<p>- Tamaño de la pantalla: 15.6 pulgadas</p>\n<p>- Disco duro HDD: 1TB</p>\n<p>- Unidad de estado sólido SSD: 128GB</p>\n<p>- Núcleos del procesador: Hexa Core</p>\n<p>- Memoria total (RAM + Intel Optane): 8 GB</p>\n<p>- Velocidad del procesador: 2.40 GHz</p>\n<p>- Velocidad máxima del procesador: 4.10 GHz</p>\n<p>- Modelo del procesador: Intel Core i5 9300H</p>",
        "value": 3199000,
        "availability": 5,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1oSI2epo4wVZkh2oA8ZfmQlpzZZja7tKA",
        "category": "Portátiles",
        "createdAt": "2020-06-28T22:48:01.208Z",
        "updatedAt": "2020-07-01T04:14:06.888Z"
      },
      {
        "objectId": "phYEBALccS",
        "name": "Portátil Hp Envy AH1006LA 13.3\"",
        "reference": "AH1006LA",
        "trademark": "HP",
        "description": "Ligera, poderosa y con diseño único con madera auténtica, la nueva HP ENVY portátil 13 está diseñada para empoderar tu vida. Con tecnologías de seguridad innovadoras y hasta 16 horas de batería, tiene tu información donde vayas.",
        "specifications": "<p>- Procesador: Intel Core i5</p>\n<p>- Memoria RAM: 8GB</p>\n<p>- Tamaño de la pantalla: 13.3 pulgadas</p>\n<p>- Disco duro HDD: No aplica</p>\n<p>- Unidad de estado sólido SSD: 256GB</p>\n<p>- Núcleos del procesador: Quad Core</p>\n<p>- Memoria total (RAM + Intel Optane): 8 GB</p>\n<p>- Velocidad del procesador: 1.6 GHz</p>\n<p>- Velocidad máxima del procesador: 3.9 GHz</p>\n<p>- Modelo del procesador: Intel Core i5-8265U</p>",
        "value": 3385000,
        "availability": 7,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1GhVW4m4AQ5G4oCntKxkpPAXFPpTKOlSN",
        "category": "Portátiles",
        "createdAt": "2020-06-28T22:51:48.311Z",
        "updatedAt": "2020-07-01T04:16:06.425Z"
      },
      {
        "objectId": "PeRPyzNlHM",
        "name": "Portátil Hp dq1005la 14\" Intel Core i7",
        "reference": "14-dq1005la",
        "trademark": "HP",
        "description": "El nuevo procesador de Intel® Core™ de 10ª Gen y almacenamiento SSD con Intel® Optane™ Memory, inicia tu laptop y aplicaciones en pocos segundos. El nuevo diseño delgado y ligero del portátil HP cuenta con batería de larga duración, perfecto para mantenerte en movimiento.",
        "specifications": "<p>- Procesador: Intel Core i7</p>\n<p>- Memoria RAM: 8GB</p>\n<p>- Tamaño de la pantalla: 14 pulgadas</p>\n<p>- Disco duro HDD: 1TB</p>\n<p>- Unidad de estado sólido SSD: 256GB</p>\n<p>- Núcleos del procesador: Hexa Core</p>\n<p>- Memoria total (RAM + Intel Optane): 8 GB</p>\n<p>- Velocidad del procesador: 1.3 Ghz</p>\n<p>- Velocidad máxima del procesador: 2.20 GHz</p>\n<p>- Modelo del procesador: Intel Core i7-1065G7</p>",
        "value": 3199000,
        "availability": 5,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1ErXIW0W9tbOPB0ZMuzFsPTBQYQRPcBqc",
        "category": "Portátiles",
        "createdAt": "2020-06-28T22:54:41.000Z",
        "updatedAt": "2020-07-01T04:17:28.731Z"
      },
      {
        "objectId": "l6i9exLVpj",
        "name": "Portátil Acer Aspire 15.6\" Intel Core i5",
        "reference": "A715-72G-57TZ",
        "trademark": "ACER",
        "description": "Procesador: Intel Core i5. Memoria RAM: 4GB. Tamaño de la pantalla: 15.6 pulgadas. Disco duro HDD: 1TB. Unidad de estado sólido SSD: 128GB",
        "specifications": "<p>- Procesador: Intel Core i5</p>\n<p>- Memoria RAM: 4GB</p>\n<p>- Tamaño de la pantalla: 15.6 pulgadas</p>\n<p>- Disco duro HDD: 1T</p>\n<p>- Unidad de estado sólido SSD: 128GB</p>\n<p>- Núcleos del procesador: Quad Core</p>\n<p>- Memoria total (RAM + Intel Optane): 4GB</p>\n<p>- Velocidad del procesador: 2.30 GHz</p>\n<p>- Velocidad máxima del procesador: 4.00 GHz</p>\n<p>- Modelo del procesador: Intel Core i5-8265U</p>",
        "value": 3899000,
        "availability": 5,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1FT3NXJQno878D2rDvNtQ9ThDPd2-qCFh",
        "category": "Portátiles",
        "createdAt": "2020-06-28T22:58:39.062Z",
        "updatedAt": "2020-07-01T04:18:58.393Z"
      },
      {
        "objectId": "NFCxxkx3UJ",
        "name": "TV AOC 55\" LED 4K Ultra HD Smart Tv",
        "reference": "55U6285",
        "trademark": "AOC",
        "description": "Conoce una experiencia de imagen a un nivel que no podrás creer. Colores intensos y contraste superior, disfruta tu televisor con una resolución 4 veces mayor que un TV Full HD. Además, su sistema Linux te permite navegar con mas agilidad y seguridad en internet.",
        "specifications": "<p>- Tamaño de la pantalla: 55 pulgadas</p>\n<p>- Resolución: 4K Ultra HD</p>\n<p>- Tecnología: LED</p>\n<p>- Conexión Bluetooth: No</p>\n<p>- Entradas USB: 2</p>\n<p>- Smart TV: Sí</p>\n<p>- Entradas HDMI: 3</p>\n<p>- Control remoto incluido: Sí</p>",
        "value": 1299900,
        "availability": 5,
        "photoUrl": "http://drive.google.com/uc?export=view&id=12o_kvMKBClVzw0jt1vaCP2n-v2CqCsAx",
        "category": "Televisores",
        "createdAt": "2020-06-28T23:03:44.871Z",
        "updatedAt": "2020-07-01T03:58:44.590Z"
      },
      {
        "objectId": "LoCZF5q1Gp",
        "name": "TV Lg 55\" OLED 4K UHD Smart Tv",
        "reference": "55B9PDB",
        "trademark": "LG",
        "description": "Con nuevo OLEDB9, La inteligencia artificial de LG ThinQ AI muchas experiencias se hacen posibles solo con tu voz .Continúa el diálogo con el reconocimiento de voz conversacional (En Español para Colombia) y obtén recomendaciones personalizadas basadas en tu experiencia. Su procesador ha sido actualizado con un algoritmo de aprendizaje profundo. Con OLED experimenta una asombrosa inmersión con detalles oscuros. Dolby transforma tu casa en una potencia de entretenimiento con imágenes y sonido HDR cinemáticos. También mejora tu experiencia de juego. Un tiempo de respuesta de 1 ms* y un Input Lag bajo. Para completar Añade un toque de clase a tu vida con Modo galería. El modo galería ofrece imágenes famosas que se actualizan por temporada.",
        "specifications": "<p>- Tamaño de la pantalla: 55 pulgadas</p>\n<p>- Resolución: 4K Ultra HD</p>\n<p>- Tecnología: OLED</p>\n<p>- Conexión Bluetooth: Sí</p>\n<p>- Entradas USB: 3</p>\n<p>- Smart TV: Sí</p>\n<p>- Entradas HDMI: 4</p>\n<p>- Control remoto incluido: Sí</p>",
        "value": 5799900,
        "availability": 10,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1kS3KiShIcnLVIlPma5sHp-k0CZJWGymu",
        "category": "Televisores",
        "createdAt": "2020-06-28T23:08:30.114Z",
        "updatedAt": "2020-07-01T04:00:10.365Z"
      },
      {
        "objectId": "cC68HHVxi8",
        "name": "TV Samsung 55\" Curvo 4K UHD Smart Tv",
        "reference": "UN55RU7300KXZL",
        "trademark": "SAMSUNG",
        "description": "HDR+: justa los niveles de contraste multicapa. PurColour: Obtén una experiencia de visión más colorida.. SmartThings, solo una aplicación para todo. One Depth: contenido para ti en una sola pantalla. Diseño: Curvas inspiradas por la naturaleza",
        "specifications": "<p>- Tamaño de la pantalla: 55 pulgadas</p>\n<p>- Resolución: 4K Ultra HD</p>\n<p>- Tecnología: LED</p>\n<p>- Conexión Bluetooth: Sí</p>\n<p>- Entradas USB: 2</p>\n<p>- Smart TV: Sí</p>\n<p>- Entradas HDMI: 3</p>\n<p>- Control remoto incluido: Sí</p>",
        "value": 1729900,
        "availability": 5,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1MAujet960qxq7ZHpCiR1dkvZcMvTnXS7",
        "category": "Televisores",
        "createdAt": "2020-06-28T23:13:31.812Z",
        "updatedAt": "2020-07-01T04:00:47.987Z"
      },
      {
        "objectId": "E1BSHk1TgE",
        "name": "TV Samsung 58\" LED 4K UHD Smart Tv",
        "reference": "58TU7000",
        "trademark": "SAMSUNG",
        "description": "El nuevo 58TU7000 Crystal UHD TV desbloquea detalles ocultos a cuatro veces la calidad de Full HD. Además, la Guía Universal lo ayuda a encontrar exactamente lo que desea ver, de manera rápida y fácil. El diseño elegante, y minimalista lo lleva a la pantalla desde cualquier ángulo, permitiendo que experimente colores cristalinos que están ajustados para brindar una imagen naturalmente nítida y vívida.",
        "specifications": "<p>- Tamaño de la pantalla: 58 pulgadas</p>\n<p>- Resolución: 4K Ultra HD</p>\n<p>- Tecnología: LED</p>\n<p>- Conexión Bluetooth: No</p>\n<p>- Entradas USB: 1</p>\n<p>- Smart TV: Sí</p>\n<p>- Entradas HDMI: 2</p>\n<p>- Control remoto incluido: Sí</p>",
        "value": 1799900,
        "availability": 10,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1g1pOfRfqq1Tyrajm5PqExsdcnysM11QE",
        "category": "Televisores",
        "createdAt": "2020-06-28T23:16:09.225Z",
        "updatedAt": "2020-07-01T04:04:08.118Z"
      },
      {
        "objectId": "wvRaDpJyX6",
        "name": "TV Lg 70\" LED 4K UHD Smart Tv",
        "reference": "70UN7310",
        "trademark": "LG",
        "description": "Este televisor LG UHD Modelo 2020, fue creado para elevar la calidad de imagen a un nuevo nivel: Cine, deportes o juegos en un televisor con \"4K Real\" los colores son realmente vivos y los detalles finos. Este año incluye un procesador que elimina el ruido y la borrosidad para crear colores y contrastes más vibrantes. Las imágenes de baja resolución se mejoran y se reproducen con una calidad cercana a 4K. El LG AI ThinQ inteligente te hace la vida aún más conveniente. ",
        "specifications": "<p>- Tamaño de la pantalla: 70 pulgadas</p>\n<p>- Resolución: 4K Ultra HD</p>\n<p>- Tecnología: LED</p>\n<p>- Conexión Bluetooth: Si</p>\n<p>- Entradas USB: 1</p>\n<p>- Smart TV: Sí</p>\n<p>- Entradas HDMI: 3</p>\n<p>- Control remoto incluido: Sí</p>",
        "value": 2999900,
        "availability": 10,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1qbbMneAh-2Fh7EWgs4taSMvsEEjOHbpV",
        "category": "Televisores",
        "createdAt": "2020-06-28T23:18:46.291Z",
        "updatedAt": "2020-07-01T04:03:42.435Z"
      },
      {
        "objectId": "auzeWYNedA",
        "name": "TV Kalley 55\" 4K UHD Smart Tv",
        "reference": "K-LED55UHDSFBT",
        "trademark": "KALLEY",
        "description": "Imagen, Diseño y Tecnología! Nuevo Smart TV de 55\" (139cm) con Resolución UltraHD (4K) y Bluetooth (solo salida audio). Certificado por Netflix y Youtube (Boton de Acceso Directo desde Control Remoto y App Presintalada y Actualizada). Incluye Netflix, Youtube, Claro Video, Wireless Display (Miracast), Explorador de Internet, App Store y Sintonizador Digital TDT (Con funciones Grabador y Timeshift). Reproductor Multimedia (Imagen, Video y Música) desde USB.",
        "specifications": "<p>- Tamaño de la pantalla: 55 pulgadas</p>\n<p>- Resolución: 4K Ultra HD</p>\n<p>- Tecnología: LED</p>\n<p>- Conexión Bluetooth: No</p>\n<p>- Entradas USB: 2</p>\n<p>- Smart TV: Sí</p>\n<p>- Entradas HDMI: 3</p>\n<p>- Control remoto incluido: Sí</p>",
        "value": 1399900,
        "availability": 10,
        "photoUrl": "http://drive.google.com/uc?export=view&id=14BZfZpi7wtQixVRt-z9H-X4WxR5etJWq",
        "category": "Televisores",
        "createdAt": "2020-06-28T23:24:18.157Z",
        "updatedAt": "2020-07-01T04:02:30.794Z"
      },
      {
        "objectId": "sDRmL89aGi",
        "name": "TV Samsung 65\" LED 4K UHD Smart Tv",
        "reference": "65TU7000",
        "trademark": "SAMSUNG",
        "description": "El nuevo 65TU7000 Crystal UHD TV desbloquea detalles ocultos a cuatro veces la calidad de Full HD. Además, la Guía Universal lo ayuda a encontrar exactamente lo que desea ver, de manera rápida y fácil. El diseño elegante, y minimalista lo lleva a la pantalla desde cualquier ángulo, permitiendo que experimente colores cristalinos que están ajustados para brindar una imagen naturalmente nítida y vívida.",
        "specifications": "<p>- Tamaño de la pantalla: 65 pulgadas</p>\n<p>- Resolución: 4K Ultra HD</p>\n<p>- Tecnología: LED</p>\n<p>- Conexión Bluetooth: No</p>\n<p>- Entradas USB: 1</p>\n<p>- Smart TV: Sí</p>\n<p>- Entradas HDMI: 2</p>\n<p>- Control remoto incluido: Sí</p>",
        "value": 2990900,
        "availability": 10,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1YQJCwop4J6mJ-0ER4Kj4Uu6xKtGYRxnL",
        "category": "Televisores",
        "createdAt": "2020-06-28T23:26:53.382Z",
        "updatedAt": "2020-07-01T04:04:28.752Z"
      },
      {
        "objectId": "EBYnUjErB3",
        "name": "TV Samsung 70\" LED 4K UHD Smart Tv",
        "reference": "70RU7100",
        "trademark": "SAMSUNG",
        "description": "Disfruta imágenes realmente nítidas con UHD 4K TV, que tiene 4 veces más pixeles que una FHD TV. Ahora podrás ver incluso los detalles más pequeños.apoyados por la tecnolgia de procesador Quad Core y la innovacion que solo Samsung te puede dar",
        "specifications": "<p>- Tamaño de la pantalla: 55 pulgadas</p>\n<p>- Resolución: 4K Ultra HD</p>\n<p>- Tecnología: LED</p>\n<p>- Conexión Bluetooth: Si</p>\n<p>- Entradas USB: 2</p>\n<p>- Smart TV: Sí</p>\n<p>- Entradas HDMI: 3</p>\n<p>- Control remoto incluido: Sí</p>",
        "value": 2799900,
        "availability": 10,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1iewSYByzY1OC_PCKJKjqOZJGUpS8N9Jw",
        "category": "Televisores",
        "createdAt": "2020-06-28T23:29:11.832Z",
        "updatedAt": "2020-07-01T04:05:05.102Z"
      },
      {
        "objectId": "oFiXk094fE",
        "name": "TV Lg 65\" LED 4K UHD Smart Tv",
        "reference": "65NANO81DNA",
        "trademark": "LG",
        "description": "LG Nanocell AI ThinQ, Colores puros. Los colores RGB puros son la clave para una calidad de imagen realista. La tecnología NanoCell aplica nanopartículas que crean colores puros al filtrar colores opacos y mejorar la pureza del espectro RGB. El procesador de cuatro núcleos 4K elimina el ruido para crear colores y contraste más dinámicos. NanoCell TV permite a los usuarios jugar y reaccionar más rápido que el oponente. Sincroniza tus sentidos con escenas en tiempo real debido a esta mejora en el Input Lag.Transforma tu TV en el \"hub\" central de tu hogar, además LG ThinQ AI te permite controlar de forma sencilla tu ecosistema del Internet de las cosas y cuenta con reconocimiento de voz natural. LG NanoCell TV hace que tu vida sea mucho más práctica. En sonido se obtiene uno virtual 4.0.",
        "specifications": "<p>- Tamaño de la pantalla: 55 pulgadas</p>\n<p>- Resolución: 4K Ultra HD</p>\n<p>- Tecnología: LED</p>\n<p>- Conexión Bluetooth: No</p>\n<p>- Entradas USB: 2</p>\n<p>- Smart TV: Sí</p>\n<p>- Entradas HDMI: 4</p>\n<p>- Control remoto incluido: Sí</p>",
        "value": 3349900,
        "availability": 8,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1A-nSpMcU6y8CXKO4PBipg2tnKP58NI4C",
        "category": "Televisores",
        "createdAt": "2020-06-28T23:35:45.527Z",
        "updatedAt": "2020-07-01T04:03:21.112Z"
      },
      {
        "objectId": "YkCvX7ISt5",
        "name": "Celular Samsung Galaxy A71 128GB",
        "reference": "Galaxy A71",
        "trademark": "SAMSUNG",
        "description": "Disfruta del mejor contenido con el display de 6.7\" Super AMOLED FHD+ y su potente bateria de 4500 mAh. Mayor potencia con una ROM: 128 GB RAM: 6 GB. Display de 6.7\" Super AMOLED con coloes más vivos. Carga rápida de 25W para estar siempre conectado.",
        "specifications": "<p>- Tamaño de la pantalla: 6.7 pulgadas</p>\n<p>- Cámara posterior: 64MP + 12MP + 5MP + 5MP</p>\n<p>- Cámara frontal: 32MP</p>\n<p>- Memoria interna: 128GB</p>\n<p>- Núcleos del procesador: Octa Core</p>\n<p>- Capacidad de la batería: 4500mAh</p>\n<p>- Carga rápida: Sí</p>\n<p>- Flash frontal: No</p>\n<p>- Cámara frontal secundaria: No</p>\n<p>- Cámara posterior secundaria: 8MP</p>\n<p>- Marca y modelo del procesador: Qualcomm Snapdragon</p>\n<p>- Velocidad del procesador: Octa Core (2.2GHz + 1.7GHz)</p>\n<p>- Memoria RAM: 6GB</p>",
        "value": 1749090,
        "availability": 10,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1oPKR0ZTU1PMKxBNovVvhostvsJQ8ALWD",
        "category": "Celulares",
        "createdAt": "2020-06-28T23:38:36.262Z",
        "updatedAt": "2020-06-30T20:56:46.421Z"
      },
      {
        "objectId": "uUBcfig1iQ",
        "name": "Celular Lg K61 128GB Gris",
        "reference": "Lg K61",
        "trademark": "LG",
        "description": "Captura tus historias favoritas a tu manera, conoce el LG K61.| Smartphone con 5 cámaras y 128 GB de memoria para una mejor experiencia y almacenamiento. Su cuádruple cámara principal + cámara de selfie te brindan una excelente resolución: cámara estándar de 48MP, gran angular de 8MP, sensor de profundidad de 5MP y lentes macro de 2MP. Una pantalla grande y vívida de FHD+ 6,53\" con Hole In y sonido envolvente 3D DTS:X que te ofrecen una experiencia inmersiva al disfrutar tus contenidos favoritos y por mucho tiempo gracias a la gran capacidad de batería de 4.000 mAh. ¡Adquiere el tuyo ahora!",
        "specifications": "<p>- Tamaño de la pantalla: 6.53 pulgadas</p>\n<p>- Cámara posterior: 48MP + 8MP + 5MP + 2MP</p>\n<p>- Cámara frontal: 16MP</p>\n<p>- Memoria interna: 128GB</p>\n<p>- Núcleos del procesador: Octa Core</p>\n<p>- Capacidad de la batería: 4000mAh</p>\n<p>- Carga rápida: No</p>\n<p>- Flash frontal: No</p>\n<p>- Cámara frontal secundaria: No</p>\n<p>- Tipo de Camara Posterior: Cuádruple</p>\n<p>- Marca y modelo del procesador: Mediatek</p>\n<p>- Velocidad del procesador: 2.3GHz</p>\n<p>- Memoria RAM: 4GB</p>",
        "value": 779900,
        "availability": 10,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1I_EBz-xayD-Q5c3aO0jBIA78BSplC2N9",
        "category": "Celulares",
        "createdAt": "2020-06-28T23:41:52.571Z",
        "updatedAt": "2020-06-30T21:23:32.735Z"
      },
      {
        "objectId": "eeI1bkY0x3",
        "name": "Celular Xiaomi Redmi Note 8 Pro 64GB",
        "reference": "Redmi Note 8 Pro",
        "trademark": "XIAOMI",
        "description": "Xiaomi con su Note 8 Pro quiere que recuerdes tus mejores momentos gracias a sus 4 cámaras sin preocuparte por la batería. Vive la experiencia de todo un gamer gracias a su procesador con refrigeración líquida. Batería de 4500 MaH con carga rápida. Convierte tu teléfono en una cartera con su NFC.",
        "specifications": "<p>- Tamaño de la pantalla: 6.5 pulgadas</p>\n<p>- Cámara posterior: 64 MP</p>\n<p>- Cámara frontal: 20MP</p>\n<p>- Memoria interna: 128GB</p>\n<p>- Núcleos del procesador: Octa Core</p>\n<p>- Capacidad de la batería: 4500mAh</p>\n<p>- Carga rápida: Sí</p>\n<p>- Flash frontal: No</p>\n<p>- Cámara frontal secundaria: No</p>\n<p>- Cámara posterior secundaria: 8MP + 2MP+ 2MP</p>\n<p>- Marca y modelo del procesador: MediaTek</p>\n<p>- Velocidad del procesador: 2 Core 2.05 GHz + 6 Core 2.0 GHz</p>\n<p>- Memoria RAM: 6GB</p>",
        "value": 1499900,
        "availability": 9,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1fT0kbismpfx_53jRqlekF_0fSBiq6aFg",
        "category": "Celulares",
        "createdAt": "2020-06-28T23:52:41.255Z",
        "updatedAt": "2020-06-30T21:24:51.469Z"
      },
      {
        "objectId": "44Z4rHNrrm",
        "name": "Celular Xiaomi Redmi 8A 32GB",
        "reference": "Redmi 8A",
        "trademark": "XIAOMI",
        "description": "El potente 8A te brindará un rendimiento óptimo para todas tus aplicaciones diarias, gracias a sus 5000 mAh de batería y un procesador 439. Cámara trasera de 12MPX para que tomes las mejores fotos. Pantalla de 6,22\" para ver tus videos favoritos.",
        "specifications": "<p>- Tamaño de la pantalla: 6.22 pulgadas</p>\n<p>- Cámara posterior: 12MP</p>\n<p>- Cámara frontal: 8MP</p>\n<p>- Memoria interna: 32GB</p>\n<p>- Núcleos del procesador: Octa Core</p>\n<p>- Capacidad de la batería: 5000mAh</p>\n<p>- Carga rápida: Si</p>\n<p>- Flash frontal: No</p>\n<p>- Cámara frontal secundaria: No</p>\n<p>- Tipo de Camara Posterior: Sencilla</p>\n<p>- Marca y modelo del procesador: Qualcomm Snapdragon</p>\n<p>- Velocidad del procesador: 4 Core 2.0 GHz + 4 Core 1.45 GHZ</p>\n<p>- Memoria RAM: 2GB</p>",
        "value": 479900,
        "availability": 16,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1KINcU07eM9gh_eoAmTgGb14pVIvMouxS",
        "category": "Celulares",
        "createdAt": "2020-06-28T23:57:19.051Z",
        "updatedAt": "2020-06-30T21:46:50.429Z"
      },
      {
        "objectId": "2FzotDyZdL",
        "name": "Celular Huawei P30 PRO DS 4G",
        "reference": "P30 PRO",
        "trademark": "HUAWEI",
        "description": "Con vistas mas amplias y detalles mas claros y nítidos, Huawei P30 Series alcanza nuevos niveles de fotografía en teléfonos inteligentes. La elegancia del cuerpo de cristal. Camara cuádruple Leica de alta precisión. Zoom Hibrido 10X. Memoria ROM de 256GB, para guardar tus mejores momentos. Memoria RAM de 8 GB, mejor rendimiento.",
        "specifications": "<p>- Tamaño de la pantalla: 6.47 pulgadas</p>\n<p>- Cámara posterior: 40MP + 20MP + 8MP</p>\n<p>- Cámara frontal: 32MP</p>\n<p>- Memoria interna: 256GB</p>\n<p>- Núcleos del procesador: Octa Core</p>\n<p>- Capacidad de la batería: 3340mAh</p>\n<p>- Carga rápida: Si</p>\n<p>- Flash frontal: No</p>\n<p>- Cámara frontal secundaria: No</p>\n<p>- Tipo de Camara Posterior: Triple</p>\n<p>- Marca y modelo del procesador: HiSilicon Kirin 710</p>\n<p>- Velocidad del procesador: 2 Core 2.6 GHz + 2 Core 1.92 GHz + 4 Core 1.8 GHz</p>\n<p>- Memoria RAM: 8GB</p>",
        "value": 2799900,
        "availability": 10,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1MH1Z94PN4w8MZMnyV_mkKqirb7mViFR8",
        "category": "Celulares",
        "createdAt": "2020-06-29T00:02:51.699Z",
        "updatedAt": "2021-10-14T02:39:00.693Z"
      },
      {
        "objectId": "BnzsBGxixU",
        "name": "TV JVC 55\" LED 4K HDR Smart Tv",
        "reference": "LT-55KD595BF",
        "trademark": "JVC",
        "description": "Tamaño de la pantalla: 55 pulgadas. Resolución: 4K HDR. Tecnología: LED. Conexión Bluetooth: No. Entradas USB: 2",
        "specifications": "<p>- Tamaño de la pantalla: 55 pulgadas</p>\n<p>- Resolución: 4K HDR</p>\n<p>- Tecnología: LED</p>\n<p>- Conexión Bluetooth: No</p>\n<p>- Entradas USB: 2</p>\n<p>- Smart TV: Sí</p>\n<p>- Entradas HDMI: 3</p>\n<p>- Control remoto incluido: Sí</p>",
        "value": 1199900,
        "availability": 7,
        "photoUrl": "http://drive.google.com/uc?export=view&id=15crVUjzX0Vp1wUhadUWtl1ugzacAeWAe",
        "category": "Televisores",
        "createdAt": "2020-07-01T00:45:02.835Z",
        "updatedAt": "2020-07-01T04:02:06.252Z"
      },
      {
        "objectId": "kHhlDZ16WU",
        "name": "Videojuego Fifa 20",
        "reference": "Fifa 20",
        "trademark": "XBOX ONE",
        "description": "EA SPORTS™ FIFA 20 muestra las dos caras del deporte rey: la prestigiosa competición profesional y el fútbol callejero más auténtico con la nueva experiencia EA SPORTS VOLTA. FIFA 20 innova en todos los aspectos con FOOTBALL INTELLIGENCE, una plataforma con un nivel de realismo en el juego sin precedentes; FIFA Ultimate Team™, que te da aún más opciones para crear el equipo de tus sueños, y EA SPORTS VOLTA, que trae de vuelta la autenticidad del fútbol a escala urbana.",
        "specifications": "<p>- Plataforma: Xbox One</p>\n<p>- Número de jugadores: Multijugador</p>\n<p>- Versión: 20</p>\n<p>- Juego en línea: Si</p>\n<p>- Idioma: Inglés</p>\n<p>- Hecho en: China</p>\n<p>- Género de videojuegos: Deportes</p>\n<p>- Clasificación: T (+9 años)</p>\n<p>- Nombre del videojuego: Fifa 20</p>",
        "value": 228000,
        "availability": 6,
        "photoUrl": "http://drive.google.com/uc?export=view&id=152cb58cbmUw8534umeDCK6-OT2SESPwl",
        "category": "Videojuegos",
        "createdAt": "2020-07-01T02:57:46.035Z",
        "updatedAt": "2020-07-01T03:04:14.527Z"
      },
      {
        "objectId": "1qSi3rOPAJ",
        "name": "Videojuego COD Infinite Warfare",
        "reference": "Call of Duty Infinite Warfare",
        "trademark": "XBOX ONE",
        "description": "Call of Duty: Infinite Warfare es un juego de acción bélica futurista que presentará guerras a gran escala con su habitual narrativa militar. Se nos ofrecerá una nueva historia donde los jugadores deberán luchar contra el Settlement Defense Front para defender nuestro modo de vida a través del Sistema Solar. Esta nueva entrega de acción en primera persona, añadirá armas futuristas, pilotaje de naves espaciales y vehículos y una nueva serie de modos de juego, que volverán a ofrecernos características online y raciones de zombis.",
        "specifications": "<p>- Plataforma: Xbox One</p>\n<p>- Número de jugadores: 1 - 4</p>\n<p>- Versión: 1</p>\n<p>- Juego en línea: Si</p>\n<p>- Idioma: Español</p>\n<p>- Hecho en: China</p>\n<p>- Género de videojuegos: Shooter en 3ra Persona</p>\n<p>- Clasificación: M (+18 años)</p>\n<p>- Nombre del videojuego: Call of Duty Infinite Warfare</p>",
        "value": 219900,
        "availability": 8,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1eo0mxfYDDfUPXI0YPWuAxXQ-xTnU3m8M",
        "category": "Videojuegos",
        "createdAt": "2020-07-01T02:59:01.075Z",
        "updatedAt": "2020-07-01T03:11:09.573Z"
      },
      {
        "objectId": "YeSnHQeYX0",
        "name": "Videojuego Mortal Kombat 11",
        "reference": "Mortal Kombat 11",
        "trademark": "XBOX ONE",
        "description": "Al igual que los dos juegos anteriores de la serie, \"Mortal Kombat 11\" es un videojuego de lucha 2.5D. Junto con el regreso de las Fatalities y Brutalities, se introducen nuevas características de juego, como Fatal Blows y Krushing Blows.",
        "specifications": "<p>- Plataforma: Xbox One</p>\n<p>- Número de jugadores: 2</p>\n<p>- Versión: 1</p>\n<p>- Juego en línea: Sí</p>\n<p>- Idioma: Español</p>\n<p>- Hecho en: China</p>\n<p>- Género de videojuegos: Lucha</p>\n<p>- Clasificación: M (+17 años)</p>\n<p>- Nombre del videojuego: Mortal Kombat 11</p>",
        "value": 239900,
        "availability": 11,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1UVil-wWdqChRkF79_rfyMvXwKnbu1Iv6",
        "category": "Videojuegos",
        "createdAt": "2020-07-01T02:59:44.661Z",
        "updatedAt": "2020-07-01T02:59:44.661Z"
      },
      {
        "objectId": "k22Oj0wA9c",
        "name": "Videojuego Mario Kart 8 Deluxe",
        "reference": "Mario Kart 8 Deluxe",
        "trademark": "NINTENDO SWITCH",
        "description": "No te pierdas la entrega del Videojuego Switch Mario Kart 8 Deluxe para Nintendo Switch y disfruta de la emoción que provocan las carreras, todo en la innovadora interfaz que ofrece la consola. ¡Lleva el tuyo y descubre una nueva forma de juego!",
        "specifications": "<p>- Plataforma: Nintendo Switch</p>\n<p>- Número de jugadores: Más de 4</p>\n<p>- Versión: 8</p>\n<p>- Juego en línea: No</p>\n<p>- Idioma: Español</p>\n<p>- Hecho en: China</p>\n<p>- Género de videojuegos: Conducción</p>\n<p>- Clasificación: E10+ (+10 años)</p>\n<p>- Nombre del videojuego: Mario Kart 8 Deluxe</p>",
        "value": 238900,
        "availability": 8,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1mmxx-C668SMEcJ9TT-5xORj6-WssEQHw",
        "category": "Videojuegos",
        "createdAt": "2020-07-01T03:29:26.028Z",
        "updatedAt": "2020-07-01T03:29:26.028Z"
      },
      {
        "objectId": "xmZ8OzXfBg",
        "name": "Videojuego Legend Zelda Link Awake",
        "reference": "Legend Zelda Link Awake",
        "trademark": "NINTENDO SWITCH",
        "description": "Link's Awakening es uno de los pocos juegos de Zelda que no tiene lugar en la tierra ficticia de Hyrule, no aparece la Princesa Zelda (aunque se menciona una vez), no se muestra la reliquia llamada Trifuerza y que no se enfrenta al principal antagonista de la serie, Ganon. En vez de eso, Link, el personaje del jugador, es sorprendido por una fuerte tormenta mientras viajaba en barco en alta mar. Es arrastrado por la corriente hasta las playas de la Isla Koholint. Más adelante, al saber que la isla está custodiada por una misteriosa criatura dormida, llamada Pez del Viento, Link deberá luchar contra monstruos y resolver una serie de rompecabezas para encontrar ocho instrumentos musicales que la despertarán. Si no lo hace, Link quedará atrapado en la Isla Koholint para siempre.",
        "specifications": "<p>- Plataforma: Nintendo Switch</p>\n<p>- Número de jugadores: Más de 4</p>\n<p>- Versión: 8</p>\n<p>- Juego en línea: Si</p>\n<p>- Idioma: Español</p>\n<p>- Hecho en: China</p>\n<p>- Género de videojuegos: Aventura</p>\n<p>- Clasificación: E10+ (+10 años)</p>\n<p>- Nombre del videojuego: Mario Kart 8 Deluxe</p>",
        "value": 259000,
        "availability": 9,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1RlqRa0Guq0178JCm2bfbDO3573UYLS7f",
        "category": "Videojuegos",
        "createdAt": "2020-07-01T03:30:13.178Z",
        "updatedAt": "2020-07-01T03:30:13.178Z"
      },
      {
        "objectId": "VrdkXsd4Xm",
        "name": "Videojuego Star Wars Pinball",
        "reference": "Star Wars Pinball",
        "trademark": "NINTENDO SWITCH",
        "description": "Puede que no sea uno de los géneros más conocidos o laureados, pero el pinball sigue teniendo una presencia muy importante en los videojuegos. Si bien en los últimos años ha sido monopolizado por Zen Studios y sus diferentes secuelas, adaptaciones y recopilaciones, se trata de una experiencia particularmente adictiva y divertida en el ocio digital, en parte por la inherente dificultad física que tenemos casi todos a la hora de disponer de una mesa de pinball real en nuestras casas y habitaciones. En cualquier caso, si algo ha hecho bien Zen Studios, ha sido ofrecer experiencias distintas en todas sus creaciones, siendo las de Star Wars las más destacadas de todas ellas.",
        "specifications": "<p>- Plataforma: Nintendo Switch</p>\n<p>- Número de jugadores: 1</p>\n<p>- Versión: 1</p>\n<p>- Juego en línea: Si</p>\n<p>- Idioma: Español</p>\n<p>- Hecho en: China</p>\n<p>- Género de videojuegos: Aventura</p>\n<p>- Clasificación: E10+ (+10 años)</p>\n<p>- Nombre del videojuego: Star Wars Pinball</p>",
        "value": 139900,
        "availability": 6,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1UirtfP6F45LoWNzUvXk5l1HqNbEJRPRf",
        "category": "Videojuegos",
        "createdAt": "2020-07-01T03:30:51.706Z",
        "updatedAt": "2020-07-01T03:30:51.706Z"
      },
      {
        "objectId": "VhD7QHQiJl",
        "name": "Celular Asus Zenfone Max M2 32G 4G",
        "reference": "Zenfone Max M2",
        "trademark": "ASUS",
        "description": "El nuevo ZenFone Max (M2) está diseñado para ir más lejos que nunca. Su pantalla completa de 6.3 pulgadas es más grande, su plataforma móvil Snapdragon ™ 632 es más rápida y su batería de alta resistencia lo libera para disfrutar al máximo de la vida. Con su sistema de doble cámara de alta calidad para fotos perfectas en píxeles, y un potente audio de alta calidad para entretenerlo, ZenFone Max es su compañero duradero para cada aventura y cada momento precioso. Con la Detección de escena de IA avanzada, puede concentrarse en el sujeto y obtener tomas perfectas en todo momento. Esto detecta automáticamente la escena o el sujeto y optimiza la configuración de la foto, brindándole una forma más simple e inteligente de capturar y compartir cada momento mágico.",
        "specifications": "<p>- Tamaño de la pantalla: 6.3 pulgadas</p>\n<p>- Cámara posterior: 13MP + 2MP</p>\n<p>- Cámara frontal: 8MP</p>\n<p>- Memoria interna: 32GB</p>\n<p>- Núcleos del procesador: Octa Core</p>\n<p>- Capacidad de la batería: 4000mAh</p>\n<p>- Carga rápida: No</p>\n<p>- Flash frontal: Si</p>\n<p>- Cámara frontal secundaria: No</p>\n<p>- Tipo de Camara Posterior: Dual</p>\n<p>- Marca y modelo del procesador: Qualcomm Snapdragon</p>\n<p>- Velocidad del procesador: 1.8GHz</p>\n<p>- Memoria RAM: 3GB</p>",
        "value": 469900,
        "availability": 10,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1ONdgmL_C3LBlK5fnrXHEeA9kUBaLKURY",
        "category": "Celulares",
        "createdAt": "2021-10-14T02:17:35.119Z",
        "updatedAt": "2021-10-14T02:17:35.119Z"
      },
      {
        "objectId": "ObEvE1NK6k",
        "name": "Celular Samsung Galaxy Note 10 256GB",
        "reference": "Galaxy Note 10",
        "trademark": "SAMSUNG",
        "description": "El resultado de 10 años de novedades pioneras en dispositivos móviles, Galaxy S10e, S10 y S10+ presentan la próxima generación de innovación móvil",
        "specifications": "<p>- Tamaño de la pantalla: 6.3 pulgadas</p>\n<p>- Cámara posterior: 16MP</p>\n<p>- Cámara frontal: 10MP</p>\n<p>- Memoria interna: 64GB</p>\n<p>- Núcleos del procesador: Octa Core</p>\n<p>- Capacidad de la batería: 3500mAh</p>\n<p>- Carga rápida: Sí</p>\n<p>- Flash frontal: Sí</p>\n<p>- Cámara frontal secundaria: No</p>\n<p>- Cámara posterior secundaria: 16MP</p>\n<p>- Marca y modelo del procesador: Snapdragon 8.55</p>\n<p>- Velocidad del procesador: 2.7 GHz</p>\n<p>- Memoria RAM: 8GB</p>",
        "value": 3499900,
        "availability": 8,
        "photoUrl": "http://drive.google.com/uc?export=view&id=1hNevOm0ufRXHmmZCjM32xAshknbLWpCI",
        "category": "Celulares",
        "createdAt": "2021-10-14T02:52:51.529Z",
        "updatedAt": "2021-10-14T02:52:51.529Z"
      }
    ]

}
